manufacturers = {
    #id: (name, shortname),
    1: ('Sequential Circuits', None),
    4: ('Moog', None),
    6: ('Lexicon', None),
    7: ('Kurzweil', None),
    15: ('Ensoniq', None),
    16: ('Oberheim', None),
    17: ('Apple', None),
    24: ('Emu', None),
    26: ('ART', None),
    34: ('Synthaxe', None),
    36: ('Hohner', None),
    41: ('PPG', None),
    43: ('SSL', None),
    47: ('Elka / General Music', 'GEM'),
    48: ('Dynacord', None),
    51: ('Clavia (Nord)', 'Clavia'),
    54: ('Cheetah', None),
    62: ('Waldorf Electronics Gmbh', 'Waldorf'),
    64: ('Kawai Musical Instruments MFG. CO. Ltd', 'Kawai'),
    65: ('Roland Corporation', 'Roland'),
    66: ('Korg Inc.', 'Korg'),
    67: ('Yamaha Corporation', 'Yamaha'),
    68: ('Casio Computer Co. Ltd', 'Casio'),
    70: ('Kamiya Studio Co. Ltd', None),
    71: ('Akai Electric Co. Ltd.', 'Akai'),
    72: ('Victor Company of Japan, Ltd.', 'JVC'),
    75: ('Fujitsu Limited', 'Fujitsu'),
    76: ('Sony Corporation', 'Sony'),
    78: ('Teac Corporation', 'Teac'),
    80: ('Matsushita Electric Industrial Co. , Ltd', 'M-Audio'),
    81: ('Fostex Corporation', 'Fostex'),
    82: ('Zoom Corporation', 'Zoom'),
    84: ('Matsushita Communication Industrial Co., Ltd.', None),
    85: ('Suzuki Musical Instruments MFG. Co., Ltd.', 'Suzuki'),
    86: ('Fuji Sound Corporation Ltd.', 'Fuji'),
    87: ('Acoustic Technical Laboratory, Inc.', None),
    89: ('Faith, Inc.', None),
    90: ('Internet Corporation', None),
    92: ('Seekers Co. Ltd.', None),
    95: ('SD Card Association', None),
    0x7D: ('Non-commercial', None),
    0x7E: ('Universal Non-Realtime', None),
    0x7F: ('Universal Realtime', None),
    (0, 0, 7): ('Digital Music Corporation', None),
    (0, 0, 14): ('Alesis', None),
    (0, 0, 21): ('KAT', None),
    (0, 0, 22): ('Opcode', None),
    (0, 0, 26): ('Allen & Heath Brenell', None),
    (0, 0, 27): ('Peavey Electronics', None),
    (0, 0, 28): ('360 Systems', None),
    (0, 0, 32): ('Axxes', None),
    (0, 0, 116): ('Ta Horng Musical Instrument', None),
    (0, 0, 117): ('e-Tek Labs (Forte Tech)', None),
    (0, 0, 118): ('Electro-Voice', None),
    (0, 0, 119): ('Midisoft Corporation', 'Midisoft'),
    (0, 0, 120): ('QSound Labs', None),
    (0, 0, 121): ('Westrex', None),
    (0, 0, 122): ('Nvidia', None),
    (0, 0, 123): ('ESS Technology', None),
    (0, 0, 124): ('Media Trix Peripherals', None),
    (0, 0, 125): ('Brooktree Corp', None),
    (0, 0, 126): ('Otari Corp', None),
    (0, 0, 127): ('Key Electronics, Inc.', None),
    (0, 1, 0): ('Shure Incorporated', None),
    (0, 1, 1): ('AuraSound', None),
    (0, 1, 2): ('Crystal Semiconductor', None),
    (0, 1, 3): ('Conexant (Rockwell)', 'Conexant'),
    (0, 1, 4): ('Silicon Graphics', 'SGI'),
    (0, 1, 5): ('M-Audio (Midiman)', None),
    (0, 1, 6): ('PreSonus', None),
    (0, 1, 8): ('Topaz Enterprises', None),
    (0, 1, 9): ('Cast Lighting', None),
    (0, 1, 10): ('Microsoft', None),
    (0, 1, 11): ('Sonic Foundry', None),
    (0, 1, 12): ('Line 6 (Fast Forward)', 'Line 6'),
    (0, 1, 13): ('Beatnik Inc', 'Beatnik'),
    (0, 1, 14): ('Van Koevering Company', None),
    (0, 1, 15): ('Altech Systems', None),
    (0, 1, 16): ('S & S Research', None),
    (0, 1, 17): ('VLSI Technology', None),
    (0, 1, 18): ('Chromatic Research', None),
    (0, 1, 19): ('Sapphire', None),
    (0, 1, 20): ('IDRC', None),
    (0, 1, 21): ('Justonic Tuning', None),
    (0, 1, 22): ('TorComp Research Inc.', None),
    (0, 1, 23): ('Newtek Inc.', None),
    (0, 1, 24): ('Sound Sculpture', None),
    (0, 1, 25): ('Walker Technical', None),
    (0, 1, 26): ('Digital Harmony (PAVO)', None),
    (0, 1, 27): ('InVision Interactive', None),
    (0, 1, 28): ('T-Square Design', None),
    (0, 1, 29): ('Nemesys Music Technology', None),
    (0, 1, 30): ('DBX Professional (Harman Intl)', 'DBX'),
    (0, 1, 31): ('Syndyne Corporation', None),
    (0, 1, 32): ('Bitheadz', None),
    (0, 1, 33): ('Cakewalk Music Software', 'Cakewalk'),
    (0, 1, 34): ('Analog Devices', None),
    (0, 1, 35): ('National Semiconductor', None),
    (0, 1, 36): ('Boom Theory / Adinolfi Alternative Percussion', None),
    (0, 1, 37): ('Virtual DSP Corporation', None),
    (0, 1, 38): ('Antares Systems', None),
    (0, 1, 39): ('Angel Software', None),
    (0, 1, 40): ('St Louis Music', None),
    (0, 1, 41): ('Lyrrus dba G-VOX', None),
    (0, 1, 42): ('Ashley Audio Inc.', None),
    (0, 1, 43): ('Vari-Lite Inc.', None),
    (0, 1, 44): ('Summit Audio Inc.', None),
    (0, 1, 45): ('Aureal Semiconductor Inc.', None),
    (0, 1, 46): ('SeaSound LLC', None),
    (0, 1, 47): ('U.S. Robotics', None),
    (0, 1, 48): ('Aurisis Research', None),
    (0, 1, 49): ('Nearfield Research', None),
    (0, 1, 50): ('FM7 Inc', None),
    (0, 1, 51): ('Swivel Systems', None),
    (0, 1, 52): ('Hyperactive Audio Systems', None),
    (0, 1, 53): ('MidiLite (Castle Studios Productions)', 'MidiLite'),
    (0, 1, 54): ('Radikal Technologies', None),
    (0, 1, 55): ('Roger Linn Design', None),
    (0, 1, 56): ('TC-Helicon Vocal Technologies', None),
    (0, 1, 57): ('Event Electronics', None),
    (0, 1, 58): ('Sonic Network Inc', None),
    (0, 1, 59): ('Realtime Music Solutions', None),
    (0, 1, 60): ('Apogee Digital', 'Apogee'),
    (0, 1, 61): ('Classical Organs, Inc.', None),
    (0, 1, 62): ('Microtools Inc.', None),
    (0, 1, 63): ('Numark Industries', None),
    (0, 1, 64): ('Frontier Design Group, LLC', None),
    (0, 1, 65): ('Recordare LLC', None),
    (0, 1, 66): ('Starr Labs', None),
    (0, 1, 67): ('Voyager Sound Inc.', None),
    (0, 1, 68): ('Manifold Labs', None),
    (0, 1, 69): ('Aviom Inc.', 'Aviom'),
    (0, 1, 70): ('Mixmeister Technology', None),
    (0, 1, 71): ('Notation Software', None),
    (0, 1, 72): ('Mercurial Communications', None),
    (0, 1, 73): ('Wave Arts', None),
    (0, 1, 74): ('Logic Sequencing Devices', None),
    (0, 1, 75): ('Axess Electronics', 'Axess'),
    (0, 1, 76): ('Muse Research', None),
    (0, 1, 77): ('Open Labs', None),
    (0, 1, 78): ('Guillemot R&D Inc', None),
    (0, 1, 79): ('Samson Technologies', None),
    (0, 1, 80): ('Electronic Theatre Controls', None),
    (0, 1, 81): ('Blackberry (RIM)', 'Blackberry'),
    (0, 1, 82): ('Mobileer', None),
    (0, 1, 83): ('Synthogy', None),
    (0, 1, 84): ('Lynx Studio Technology Inc.', None),
    (0, 1, 85): ('Damage Control Engineering LLC', None),
    (0, 1, 86): ('Yost Engineering, Inc.', None),
    (0, 1, 87): ('Brooks & Forsman Designs LLC / DrumLite', None),
    (0, 1, 88): ('Infinite Response', None),
    (0, 1, 89): ('Garritan Corp', None),
    (0, 1, 90): ('Plogue Art et Technologie, Inc', None),
    (0, 1, 91): ('RJM Music Technology', None),
    (0, 1, 92): ('Custom Solutions Software', None),
    (0, 1, 93): ('Sonarcana LLC', None),
    (0, 1, 94): ('Centrance', None),
    (0, 1, 95): ('Kesumo LLC', None),
    (0, 1, 96): ('Stanton (Gibson)', None),
    (0, 1, 97): ('Livid Instruments', None),
    (0, 1, 98): ('First Act / 745 Media', None),
    (0, 1, 99): ('Pygraphics, Inc.', None),
    (0, 1, 100): ('Panadigm Innovations Ltd', None),
    (0, 1, 101): ('Avedis Zildjian Co', None),
    (0, 1, 102): ('Auvital Music Corp', None),
    (0, 1, 103): ('Inspired Instruments Inc', None),
    (0, 1, 104): ('Chris Grigg Designs', None),
    (0, 1, 105): ('Slate Digital LLC', None),
    (0, 1, 106): ('Mixware', None),
    (0, 1, 107): ('Social Entropy', None),
    (0, 1, 108): ('Source Audio LLC', None),
    (0, 1, 109): ('Ernie Ball / Music Man', None),
    (0, 1, 110): ('Fishman Transducers', None),
    (0, 1, 111): ('Custom Audio Electronics', None),
    (0, 1, 112): ('American Audio/DJ', None),
    (0, 1, 113): ('Mega Control Systems', None),
    (0, 1, 114): ('Kilpatrick Audio', None),
    (0, 1, 115): ('iConnectivity', None),
    (0, 1, 116): ('Fractal Audio', None),
    (0, 1, 117): ('NetLogic Microsystems', None),
    (0, 1, 118): ('Music Computing', None),
    (0, 1, 119): ('Nektar Technology Inc', None),
    (0, 1, 120): ('Zenph Sound Innovations', None),
    (0, 1, 121): ('DJTechTools.com', None),
    (0, 1, 122): ('Rezonance Labs', None),
    (0, 1, 123): ('Decibel Eleven', None),
    (0, 1, 124): ('CNMAT', None),
    (0, 1, 125): ('Media Overkill', None),
    (0, 1, 126): ('Confusionists LLC', None),
    (0, 32, 39): ('Acorn Computer', None),
    (0, 32, 41): ('Focusrite/Novation', 'Novation'),
    (0, 32, 42): ('Samkyung Mechatronics', None),
    (0, 32, 43): ('Medeli Electronics Co.', None),
    (0, 32, 44): ('Charlie Lab SRL', None),
    (0, 32, 45): ('Blue Chip Music Technology', None),
    (0, 32, 46): ('BEE OH Corp', None),
    (0, 32, 47): ('LG Semicon America', None),
    (0, 32, 48): ('TESI', None),
    (0, 32, 49): ('EMAGIC', None),
    (0, 32, 50): ('Behringer GmbH', 'Behringer'),
    (0, 32, 51): ('Access Music Electronics', 'Access'),
    (0, 32, 52): ('Synoptic', None),
    (0, 32, 53): ('Hanmesoft', None),
    (0, 32, 54): ('Terratec Electronic GmbH', None),
    (0, 32, 55): ('Proel SpA', None),
    (0, 32, 56): ('IBK MIDI', None),
    (0, 32, 57): ('IRCAM', None),
    (0, 32, 58): ('Propellerhead Software', None),
    (0, 32, 59): ('Red Sound Systems Ltd', None),
    (0, 32, 60): ('Elektron ESI AB', None),
    (0, 32, 61): ('Sintefex Audio', None),
    (0, 32, 62): ('MAM (Music and More)', 'MAM'),
    (0, 32, 63): ('Amsaro GmbH', None),
    (0, 32, 64): ('CDS Advanced Technology BV', None),
    (0, 32, 65): ('Touched By Sound GmbH', None),
    (0, 32, 66): ('DSP Arts', None),
    (0, 32, 67): ('Phil Rees Music Tech', None),
    (0, 32, 68): ('Stamer Musikanlagen GmbH', None),
    (0, 32, 69): ('Musical Muntaner S.A. dba Soundart', None),
    (0, 32, 70): ('C-Mexx Software', 'C-Mexx'),
    (0, 32, 71): ('Klavis Technologies', None),
    (0, 32, 72): ('Noteheads AB', None),
    (0, 32, 73): ('Algorithmix', None),
    (0, 32, 74): ('Skrydstrup R&D', None),
    (0, 32, 75): ('Professional Audio Company', None),
    (0, 32, 76): ('NewWave Labs (MadWaves)', None),
    (0, 32, 77): ('Vermona', None),
    (0, 32, 78): ('Nokia', None),
    (0, 32, 79): ('Wave Idea', None),
    (0, 32, 80): ('Hartmann GmbH', None),
    (0, 32, 81): ("Lion's Tracs", None),
    (0, 32, 82): ('Analogue Systems', None),
    (0, 32, 83): ('Focal-JMlab', None),
    (0, 32, 84): ('Ringway Electronics (Chang-Zhou) Co Ltd', None),
    (0, 32, 85): ('Faith Technologies (Digiplug)', None),
    (0, 32, 86): ('Showworks', None),
    (0, 32, 87): ('Manikin Electronic', 'Manikin'),
    (0, 32, 88): ('1 Come Tech', None),
    (0, 32, 89): ('Phonic Corp', None),
    (0, 32, 90): ('Dolby Australia (Lake)', None),
    (0, 32, 91): ('Silansys Technologies', None),
    (0, 32, 92): ('Winbond Electronics', None),
    (0, 32, 93): ('Cinetix Medien und Interface GmbH', None),
    (0, 32, 94): ('A&G Soluzioni Digitali', None),
    (0, 32, 95): ('Sequentix Music Systems', None),
    (0, 32, 96): ('Oram Pro Audio', None),
    (0, 32, 97): ('Be4 Ltd', None),
    (0, 32, 98): ('Infection Music', None),
    (0, 32, 99): ('Central Music Co. (CME)', 'CME'),
    (0, 32, 100): ('genoQs Machines GmbH', None),
    (0, 32, 101): ('Medialon', None),
    (0, 32, 102): ('Waves Audio Ltd', None),
    (0, 32, 103): ('Jerash Labs', None),
    (0, 32, 104): ('Da Fact', None),
    (0, 32, 105): ('Elby Designs', None),
    (0, 32, 106): ('Spectral Audio', None),
    (0, 32, 107): ('Arturia', None),
    (0, 32, 108): ('Vixid', None),
    (0, 32, 109): ('C-Thru Music', None),
    (0, 32, 110): ('Ya Horng Electronic Co LTD', None),
    (0, 32, 111): ('SM Pro Audio', None),
    (0, 32, 112): ('OTO MACHINES', None),
    (0, 32, 113): ('ELZAB S.A., G LAB', None),
    (0, 32, 114): ('Blackstar Amplification Ltd', None),
    (0, 32, 115): ('M3i Technologies GmbH', None),
    (0, 32, 116): ('Gemalto (from Xiring)', None),
    (0, 32, 117): ('Prostage SL', None),
    (0, 32, 118): ('Teenage Engineering', None),
    (0, 32, 119): ('Tobias Erichsen Consulting', None),
    (0, 32, 120): ('Nixer Ltd', None),
    (0, 32, 121): ('Hanpin Electron Co Ltd', None),
    (0, 32, 122): ('"MIDI-hardware" R.Sowa', None),
    (0, 32, 123): ('Beyond Music Industrial Ltd', None),
    (0, 32, 124): ('Kiss Box B.V.', None),
    (0, 32, 125): ('Misa Digital Technologies Ltd', None),
    (0, 32, 126): ('AI Musics Technology Inc', None),
    (0, 32, 127): ('Serato Inc LP', None),
    (0, 33, 0): ('Limex Music Handles GmbH', None),
    (0, 33, 1): ('Kyodday/Tokai', None),
    (0, 33, 2): ('Mutable Instruments', None),
    (0, 33, 3): ('PreSonus Software Ltd', 'PreSonus'),
    (0, 33, 4): ('Xiring', None),
    (0, 33, 5): ('Fairlight Instruments Pty Ltd', 'Fairlight'),
    (0, 33, 6): ('Musicom Lab', None),
    (0, 33, 7): ('VacoLoco', None),
    (0, 33, 8): ('RWA (Hong Kong) Limited', None),
    (0, 33, 9): ('Native Instruments', 'NI'),
    (0, 33, 10): ('Naonext', None),
    (0, 33, 11): ('MFB', None),
    (0, 33, 12): ('Teknel Research', None),
    (0, 33, 13): ('Ploytec GmbH', 'Ploytec'),
    (0, 33, 14): ('Surfin Kangaroo Studio', None),
    (0, 33, 15): ('Philips Electronics HK Ltd', 'Philips'),
    (0, 33, 16): ('ROLI Ltd', None),
    (0, 64, 0): ('Crimson Technology Inc.', None),
    (0, 64, 1): ('Softbank Mobile Corp', None),
    (0, 64, 3): ('D&M Holdings Inc.', None)
}
