name: Build sdist and wheels for testing purposes

on:
  pull_request:
    branches:
      - master

jobs:
  build_sdist:
   name: Build sdist
   runs-on: ubuntu-latest
   steps:

   - uses: actions/checkout@v3
     with:
       submodules: true

   - name: Install ninja
     run: pipx install ninja

   - name: Install alsa deps
     run: sudo apt-get install libasound2-dev

   - name: Build sdist
     run: pipx run build --sdist

   - name: Check metadata
     run: pipx run twine check --strict dist/*

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:

    - uses: actions/checkout@v3
      with:
        submodules: true

    - uses: ilammy/msvc-dev-cmd@v1
      if: matrix.os == 'windows-latest'

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.12.3

  build_arch_wheels:
   name: Build wheels on Linux ${{ matrix.arch }}
   runs-on: ubuntu-20.04
   strategy:
     matrix:
       arch: [aarch64]
   steps:

   - uses: actions/checkout@v3
     with:
       submodules: true

   - uses: docker/setup-qemu-action@v2
     with:
       platforms: all

   - uses: pypa/cibuildwheel@v2.12.3
     env:
       CIBW_ARCHS: ${{ matrix.arch }}

   - name: Verify clean directory
     run: git diff --exit-code
     shell: bash

