name: Build and test wheels

on:
  push:
    branches:
      - 'feat/**'

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest]
    steps:

    - uses: actions/checkout@v3
      with:
        submodules: true

    - uses: ilammy/msvc-dev-cmd@v1
      if: matrix.os == 'windows-latest'

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.13

    - uses: actions/upload-artifact@v3
      with:
        path: wheelhouse/*.whl
